package com.paisabrain.app.safety

import android.content.Context
import android.content.SharedPreferences
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.format.DateTimeFormatter
import java.time.temporal.ChronoMinutes
import kotlin.math.abs

/**
 * Detects potentially fraudulent or suspicious transactions using
 * pattern analysis and behavioral heuristics.
 *
 * This operates entirely on-device with no external API calls.
 * It analyzes transaction patterns against the user's normal behavior
 * to flag anomalies that may indicate unauthorized activity.
 *
 * Detection methods:
 * - Unusual transaction times (late night activity)
 * - Unusual amounts (significantly above average)
 * - Unknown merchants with high amounts
 * - Rapid successive debits
 * - International transaction patterns
 * - Location anomalies
 *
 * All analysis is privacy-preserving and runs locally.
 */
class FraudDetector(private val context: Context) {

    companion object {
        private const val PREFS_NAME = "fraud_detector_prefs"
        private const val KEY_ALERTS = "fraud_alerts"
        private const val KEY_KNOWN_MERCHANTS = "known_merchants"
        private const val KEY_TRANSACTION_HISTORY = "recent_transactions"
        private const val KEY_AVERAGE_AMOUNT = "average_transaction_amount"
        private const val KEY_TRANSACTION_COUNT = "transaction_count"
        private const val KEY_DISMISSED_ALERTS = "dismissed_alerts"

        /** Late night hours considered unusual (2 AM to 5 AM) */
        private val UNUSUAL_TIME_START = LocalTime.of(2, 0)
        private val UNUSUAL_TIME_END = LocalTime.of(5, 0)

        /** Multiplier above average that triggers amount flag */
        private const val AMOUNT_MULTIPLIER_THRESHOLD = 3.0

        /** Number of rapid transactions that trigger flag */
        private const val RAPID_DEBIT_COUNT = 3

        /** Time window for rapid debits (in minutes) */
        private const val RAPID_DEBIT_WINDOW_MINUTES = 5L

        /** Amount threshold for unknown merchant flagging (in rupees) */
        private const val UNKNOWN_MERCHANT_AMOUNT_THRESHOLD = 5000.0

        /** Maximum alerts to store */
        private const val MAX_STORED_ALERTS = 100
    }

    private val prefs: SharedPreferences =
        context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
    private val gson = Gson()
    private val dateTimeFormatter = DateTimeFormatter.ISO_LOCAL_DATE_TIME

    /**
     * Severity levels for fraud alerts.
     *
     * @property displayName Human-readable severity label
     * @property color Hex color for UI (red/orange/yellow)
     * @property priority Numeric priority for sorting (higher = more severe)
     */
    enum class Severity(val displayName: String, val color: String, val priority: Int) {
        /** Slightly unusual but likely legitimate */
        LOW(
            displayName = "Unusual",
            color = "#FFC107",
            priority = 1
        ),

        /** Suspicious pattern that warrants attention */
        MEDIUM(
            displayName = "Suspicious",
            color = "#FF9800",
            priority = 2
        ),

        /** Strong indicators of potential fraud — immediate action recommended */
        HIGH(
            displayName = "Likely Fraud",
            color = "#F44336",
            priority = 3
        )
    }

    /**
     * Types of fraud detection rules.
     */
    enum class DetectionType(val displayName: String, val emoji: String) {
        UNUSUAL_TIME("Unusual Time", "🌙"),
        UNUSUAL_AMOUNT("Unusual Amount", "💸"),
        UNKNOWN_MERCHANT("Unknown Merchant", "❓"),
        RAPID_DEBITS("Rapid Debits", "⚡"),
        INTERNATIONAL("International Transaction", "🌍"),
        LOCATION_ANOMALY("Location Anomaly", "📍")
    }

    /**
     * Represents a single financial transaction for analysis.
     *
     * @property id Unique transaction identifier
     * @property amount Transaction amount (positive = debit, negative = credit)
     * @property merchant Merchant or recipient name
     * @property timestamp When the transaction occurred (ISO datetime)
     * @property category Spending category if known
     * @property isInternational Whether this is an international transaction
     * @property location City/country if available
     */
    data class Transaction(
        val id: String,
        val amount: Double,
        val merchant: String,
        val timestamp: String,
        val category: String = "",
        val isInternational: Boolean = false,
        val location: String = ""
    )

    /**
     * A fraud alert generated by the detection system.
     *
     * @property id Unique alert identifier
     * @property transaction The transaction that triggered the alert
     * @property severity How serious the alert is
     * @property detectionType What kind of pattern was detected
     * @property reason Human-readable explanation of why this was flagged
     * @property suggestedAction What the user should do
     * @property timestamp When the alert was generated
     * @property isDismissed Whether the user has dismissed this alert
     * @property isConfirmedFraud Whether user confirmed this was fraudulent
     */
    data class FraudAlert(
        val id: String,
        val transaction: Transaction,
        val severity: Severity,
        val detectionType: DetectionType,
        val reason: String,
        val suggestedAction: String,
        val timestamp: String,
        val isDismissed: Boolean = false,
        val isConfirmedFraud: Boolean = false
    )

    /**
     * Result of analyzing a transaction.
     *
     * @property isSafe Whether no issues were detected
     * @property alerts List of alerts generated (may be multiple per transaction)
     * @property overallSeverity The highest severity among all alerts
     */
    data class AnalysisResult(
        val isSafe: Boolean,
        val alerts: List<FraudAlert>,
        val overallSeverity: Severity?
    )

    /**
     * Steps to take when fraud is suspected.
     */
    data class EmergencySteps(
        val immediateActions: List<String>,
        val followUpActions: List<String>,
        val preventionTips: List<String>
    )

    // ─────────────────────────────────────────────────────────────
    // Public API
    // ─────────────────────────────────────────────────────────────

    /**
     * Analyzes a single transaction for potential fraud indicators.
     * Runs all detection rules and returns any alerts generated.
     *
     * @param transaction The transaction to analyze
     * @return Analysis result with any alerts
     */
    fun analyzeTransaction(transaction: Transaction): AnalysisResult {
        val alerts = mutableListOf<FraudAlert>()

        // Run all detection checks
        checkUnusualTime(transaction)?.let { alerts.add(it) }
        checkUnusualAmount(transaction)?.let { alerts.add(it) }
        checkUnknownMerchant(transaction)?.let { alerts.add(it) }
        checkRapidDebits(transaction)?.let { alerts.add(it) }
        checkInternational(transaction)?.let { alerts.add(it) }

        // Record this transaction for future pattern analysis
        recordTransaction(transaction)

        // Store any alerts generated
        if (alerts.isNotEmpty()) {
            storeAlerts(alerts)
        }

        val overallSeverity = alerts.maxByOrNull { it.severity.priority }?.severity

        return AnalysisResult(
            isSafe = alerts.isEmpty(),
            alerts = alerts,
            overallSeverity = overallSeverity
        )
    }

    /**
     * Analyzes a batch of transactions (e.g., after syncing).
     *
     * @param transactions List of transactions to analyze
     * @return Map of transaction ID to analysis result (only flagged ones)
     */
    fun analyzeBatch(transactions: List<Transaction>): Map<String, AnalysisResult> {
        val flagged = mutableMapOf<String, AnalysisResult>()

        transactions.forEach { transaction ->
            val result = analyzeTransaction(transaction)
            if (!result.isSafe) {
                flagged[transaction.id] = result
            }
        }

        return flagged
    }

    /**
     * Gets all active (non-dismissed) fraud alerts.
     *
     * @return List of alerts sorted by severity (highest first)
     */
    fun getActiveAlerts(): List<FraudAlert> {
        return loadAlerts()
            .filter { !it.isDismissed }
            .sortedByDescending { it.severity.priority }
    }

    /**
     * Gets all alerts including dismissed ones.
     *
     * @return Complete alert history
     */
    fun getAllAlerts(): List<FraudAlert> {
        return loadAlerts().sortedByDescending { it.timestamp }
    }

    /**
     * Dismisses an alert (user reviewed and confirmed it's legitimate).
     *
     * @param alertId The alert ID to dismiss
     */
    fun dismissAlert(alertId: String) {
        val alerts = loadAlertsMutable()
        val index = alerts.indexOfFirst { it.id == alertId }
        if (index >= 0) {
            alerts[index] = alerts[index].copy(isDismissed = true)
            saveAlerts(alerts)
        }

        // Add merchant to known list if it was an unknown merchant alert
        val alert = alerts.find { it.id == alertId }
        if (alert?.detectionType == DetectionType.UNKNOWN_MERCHANT) {
            addKnownMerchant(alert.transaction.merchant)
        }
    }

    /**
     * Confirms an alert as actual fraud.
     *
     * @param alertId The alert ID to confirm
     */
    fun confirmFraud(alertId: String) {
        val alerts = loadAlertsMutable()
        val index = alerts.indexOfFirst { it.id == alertId }
        if (index >= 0) {
            alerts[index] = alerts[index].copy(isConfirmedFraud = true)
            saveAlerts(alerts)
        }
    }

    /**
     * Gets emergency steps to take when fraud is confirmed.
     * These are generic steps that apply to any financial institution.
     *
     * @return Structured emergency response steps
     */
    fun getEmergencySteps(): EmergencySteps {
        return EmergencySteps(
            immediateActions = listOf(
                "Block your card immediately — call the number on the back of your card",
                "If you have a banking app, use the instant card lock/freeze feature",
                "Do not share any OTP or verification codes with anyone calling you",
                "Screenshot the fraudulent transaction(s) for your records",
                "Change your account passwords and PINs immediately"
            ),
            followUpActions = listOf(
                "File a dispute with your bank within 24 hours",
                "File a complaint at cybercrime.gov.in or call 1930 (national helpline)",
                "Request a new card with a different number",
                "Monitor your account for additional unauthorized transactions",
                "Check if any auto-pay services need to be updated with new card details",
                "Keep a written record of all communication with your bank"
            ),
            preventionTips = listOf(
                "Enable transaction alerts for all amounts",
                "Set daily transaction limits on your cards",
                "Never share card details, CVV, OTP, or PIN with anyone",
                "Use virtual cards for online purchases when available",
                "Regularly review your transaction history",
                "Be cautious of calls claiming to be from your bank — they will never ask for OTP",
                "Enable two-factor authentication wherever possible"
            )
        )
    }

    /**
     * Gets card blocking instructions (generic, no brand names).
     *
     * @return List of steps to block a compromised card
     */
    fun getCardBlockingSteps(): List<String> {
        return listOf(
            "1. Locate the customer service number on the back of your card",
            "2. Call immediately — most banks have 24/7 helplines for card blocking",
            "3. Tell the representative you need to block your card due to suspected fraud",
            "4. Note down the complaint/reference number provided",
            "5. If available, use your banking app's instant card lock feature",
            "6. Request confirmation via SMS/email that the card has been blocked",
            "7. Ask about the timeline for issuing a replacement card",
            "8. Inquire about the dispute resolution process for fraudulent charges"
        )
    }

    /**
     * Registers a merchant as known/trusted (won't flag in future).
     *
     * @param merchantName The merchant name to trust
     */
    fun addKnownMerchant(merchantName: String) {
        val merchants = loadKnownMerchants().toMutableSet()
        merchants.add(merchantName.lowercase().trim())
        prefs.edit().putStringSet(KEY_KNOWN_MERCHANTS, merchants).apply()
    }

    /**
     * Removes a merchant from the trusted list.
     *
     * @param merchantName The merchant name to un-trust
     */
    fun removeKnownMerchant(merchantName: String) {
        val merchants = loadKnownMerchants().toMutableSet()
        merchants.remove(merchantName.lowercase().trim())
        prefs.edit().putStringSet(KEY_KNOWN_MERCHANTS, merchants).apply()
    }

    /**
     * Gets detection statistics.
     *
     * @return Map with stats about alerts generated, confirmed fraud, etc.
     */
    fun getStats(): Map<String, Any> {
        val allAlerts = loadAlerts()
        return mapOf(
            "totalAlerts" to allAlerts.size,
            "activeAlerts" to allAlerts.count { !it.isDismissed },
            "dismissedAlerts" to allAlerts.count { it.isDismissed },
            "confirmedFraud" to allAlerts.count { it.isConfirmedFraud },
            "highSeverity" to allAlerts.count { it.severity == Severity.HIGH },
            "mediumSeverity" to allAlerts.count { it.severity == Severity.MEDIUM },
            "lowSeverity" to allAlerts.count { it.severity == Severity.LOW },
            "knownMerchants" to loadKnownMerchants().size,
            "transactionsAnalyzed" to prefs.getInt(KEY_TRANSACTION_COUNT, 0)
        )
    }

    /**
     * Updates the running average transaction amount with a new data point.
     * Used internally to calibrate the "unusual amount" detector.
     *
     * @param amount The new transaction amount to incorporate
     */
    fun updateAverageAmount(amount: Double) {
        val currentAvg = prefs.getFloat(KEY_AVERAGE_AMOUNT, 0f).toDouble()
        val count = prefs.getInt(KEY_TRANSACTION_COUNT, 0)

        val newCount = count + 1
        val newAvg = if (count == 0) amount
        else ((currentAvg * count) + amount) / newCount

        prefs.edit()
            .putFloat(KEY_AVERAGE_AMOUNT, newAvg.toFloat())
            .putInt(KEY_TRANSACTION_COUNT, newCount)
            .apply()
    }

    /**
     * Clears all fraud detection data. Use with caution.
     */
    fun clearAllData() {
        prefs.edit().clear().apply()
    }

    // ─────────────────────────────────────────────────────────────
    // Detection Rules
    // ─────────────────────────────────────────────────────────────

    /**
     * Checks if a transaction occurred during unusual hours (2 AM - 5 AM).
     */
    private fun checkUnusualTime(transaction: Transaction): FraudAlert? {
        val time = try {
            LocalDateTime.parse(transaction.timestamp, dateTimeFormatter).toLocalTime()
        } catch (e: Exception) {
            return null
        }

        if (time.isAfter(UNUSUAL_TIME_START) && time.isBefore(UNUSUAL_TIME_END)) {
            val severity = if (transaction.amount > 10000) Severity.MEDIUM else Severity.LOW

            return FraudAlert(
                id = "alert_${transaction.id}_time",
                transaction = transaction,
                severity = severity,
                detectionType = DetectionType.UNUSUAL_TIME,
                reason = "Transaction at ${time.hour}:${time.minute.toString().padStart(2, '0')} — " +
                        "most of your transactions happen during daytime hours. " +
                        "Late-night transactions can indicate unauthorized card usage.",
                suggestedAction = if (severity == Severity.MEDIUM) {
                    "Check if you recognize this transaction. If not, consider blocking your card."
                } else {
                    "Verify this was you. Late-night transactions are sometimes legitimate (online shopping, travel)."
                },
                timestamp = LocalDateTime.now().format(dateTimeFormatter)
            )
        }
        return null
    }

    /**
     * Checks if the transaction amount is unusually high compared to average.
     */
    private fun checkUnusualAmount(transaction: Transaction): FraudAlert? {
        val averageAmount = prefs.getFloat(KEY_AVERAGE_AMOUNT, 0f).toDouble()
        val transactionCount = prefs.getInt(KEY_TRANSACTION_COUNT, 0)

        // Need at least 10 transactions to establish a baseline
        if (transactionCount < 10 || averageAmount <= 0) return null

        val multiplier = transaction.amount / averageAmount

        if (multiplier >= AMOUNT_MULTIPLIER_THRESHOLD) {
            val severity = when {
                multiplier >= 10.0 -> Severity.HIGH
                multiplier >= 5.0 -> Severity.MEDIUM
                else -> Severity.LOW
            }

            return FraudAlert(
                id = "alert_${transaction.id}_amount",
                transaction = transaction,
                severity = severity,
                detectionType = DetectionType.UNUSUAL_AMOUNT,
                reason = "This transaction of ₹${formatAmount(transaction.amount)} is " +
                        "${multiplier.toInt()}x your average spending of ₹${formatAmount(averageAmount)}. " +
                        "Unusually large transactions can indicate unauthorized access.",
                suggestedAction = when (severity) {
                    Severity.HIGH -> "Block your card immediately and contact your bank. " +
                            "This is significantly above your normal spending pattern."
                    Severity.MEDIUM -> "Verify this transaction immediately. If you don't recognize it, " +
                            "block your card using the number on the back."
                    Severity.LOW -> "Check if you recognize this purchase. Large but not extreme — " +
                            "could be a planned expense."
                },
                timestamp = LocalDateTime.now().format(dateTimeFormatter)
            )
        }
        return null
    }

    /**
     * Checks if the merchant is unknown AND the amount is high.
     */
    private fun checkUnknownMerchant(transaction: Transaction): FraudAlert? {
        val knownMerchants = loadKnownMerchants()
        val merchantLower = transaction.merchant.lowercase().trim()

        if (merchantLower in knownMerchants) return null
        if (transaction.amount < UNKNOWN_MERCHANT_AMOUNT_THRESHOLD) return null

        val severity = when {
            transaction.amount > 20000 -> Severity.HIGH
            transaction.amount > 10000 -> Severity.MEDIUM
            else -> Severity.LOW
        }

        return FraudAlert(
            id = "alert_${transaction.id}_merchant",
            transaction = transaction,
            severity = severity,
            detectionType = DetectionType.UNKNOWN_MERCHANT,
            reason = "First-time transaction with '${transaction.merchant}' for ₹${formatAmount(transaction.amount)}. " +
                    "You've never transacted with this merchant before, and the amount is significant.",
            suggestedAction = "Check if you recognize this merchant. " +
                    "If this is legitimate, you can mark it as known. " +
                    "If not, contact your bank immediately.",
            timestamp = LocalDateTime.now().format(dateTimeFormatter)
        )
    }

    /**
     * Checks for rapid successive debit transactions (possible card skimming).
     */
    private fun checkRapidDebits(transaction: Transaction): FraudAlert? {
        val recentTransactions = loadRecentTransactions()

        val transactionTime = try {
            LocalDateTime.parse(transaction.timestamp, dateTimeFormatter)
        } catch (e: Exception) {
            return null
        }

        // Count transactions in the last N minutes
        val recentCount = recentTransactions.count { recent ->
            try {
                val recentTime = LocalDateTime.parse(recent.timestamp, dateTimeFormatter)
                val minutesDiff = abs(
                    java.time.Duration.between(recentTime, transactionTime).toMinutes()
                )
                minutesDiff <= RAPID_DEBIT_WINDOW_MINUTES && recent.amount > 0
            } catch (e: Exception) {
                false
            }
        }

        if (recentCount >= RAPID_DEBIT_COUNT - 1) { // -1 because current transaction counts too
            val totalAmount = recentTransactions
                .filter { recent ->
                    try {
                        val recentTime = LocalDateTime.parse(recent.timestamp, dateTimeFormatter)
                        val minutesDiff = abs(
                            java.time.Duration.between(recentTime, transactionTime).toMinutes()
                        )
                        minutesDiff <= RAPID_DEBIT_WINDOW_MINUTES
                    } catch (e: Exception) {
                        false
                    }
                }
                .sumOf { it.amount } + transaction.amount

            return FraudAlert(
                id = "alert_${transaction.id}_rapid",
                transaction = transaction,
                severity = Severity.HIGH,
                detectionType = DetectionType.RAPID_DEBITS,
                reason = "${recentCount + 1} transactions within $RAPID_DEBIT_WINDOW_MINUTES minutes " +
                        "totaling ₹${formatAmount(totalAmount)}. " +
                        "Rapid successive debits are a strong indicator of card compromise or skimming.",
                suggestedAction = "Block your card immediately! Multiple rapid transactions " +
                        "are a common sign of card fraud. Call the number on the back of your card NOW.",
                timestamp = LocalDateTime.now().format(dateTimeFormatter)
            )
        }
        return null
    }

    /**
     * Checks for international transaction patterns.
     */
    private fun checkInternational(transaction: Transaction): FraudAlert? {
        if (!transaction.isInternational) return null

        // Check if user typically makes international transactions
        val recentTransactions = loadRecentTransactions()
        val recentInternational = recentTransactions.count { it.isInternational }
        val isUnusual = recentInternational == 0 // No recent international transactions

        if (isUnusual) {
            val severity = when {
                transaction.amount > 50000 -> Severity.HIGH
                transaction.amount > 10000 -> Severity.MEDIUM
                else -> Severity.LOW
            }

            return FraudAlert(
                id = "alert_${transaction.id}_intl",
                transaction = transaction,
                severity = severity,
                detectionType = DetectionType.INTERNATIONAL,
                reason = "International transaction of ₹${formatAmount(transaction.amount)} " +
                        "${if (transaction.location.isNotEmpty()) "from ${transaction.location}" else ""}. " +
                        "You don't typically make international purchases, which makes this unusual.",
                suggestedAction = if (severity == Severity.HIGH) {
                    "If you're not currently abroad or didn't make an international purchase, " +
                            "block your card immediately."
                } else {
                    "Verify this is your transaction. If you're traveling or made an online " +
                            "purchase from an international seller, this may be normal."
                },
                timestamp = LocalDateTime.now().format(dateTimeFormatter)
            )
        }
        return null
    }

    // ─────────────────────────────────────────────────────────────
    // Persistence Helpers
    // ─────────────────────────────────────────────────────────────

    private fun loadAlerts(): List<FraudAlert> {
        val json = prefs.getString(KEY_ALERTS, null) ?: return emptyList()
        return try {
            val type = object : TypeToken<List<FraudAlert>>() {}.type
            gson.fromJson(json, type)
        } catch (e: Exception) {
            emptyList()
        }
    }

    private fun loadAlertsMutable(): MutableList<FraudAlert> {
        return loadAlerts().toMutableList()
    }

    private fun saveAlerts(alerts: List<FraudAlert>) {
        val trimmed = if (alerts.size > MAX_STORED_ALERTS) {
            alerts.takeLast(MAX_STORED_ALERTS)
        } else {
            alerts
        }
        prefs.edit().putString(KEY_ALERTS, gson.toJson(trimmed)).apply()
    }

    private fun storeAlerts(newAlerts: List<FraudAlert>) {
        val existing = loadAlertsMutable()
        existing.addAll(newAlerts)
        saveAlerts(existing)
    }

    private fun loadKnownMerchants(): Set<String> {
        return prefs.getStringSet(KEY_KNOWN_MERCHANTS, emptySet()) ?: emptySet()
    }

    private fun recordTransaction(transaction: Transaction) {
        val recent = loadRecentTransactionsMutable()
        recent.add(transaction)

        // Keep only last 50 for pattern analysis
        val trimmed = if (recent.size > 50) {
            recent.takeLast(50).toMutableList()
        } else {
            recent
        }

        prefs.edit().putString(KEY_TRANSACTION_HISTORY, gson.toJson(trimmed)).apply()

        // Update average
        if (transaction.amount > 0) {
            updateAverageAmount(transaction.amount)
        }
    }

    private fun loadRecentTransactions(): List<Transaction> {
        val json = prefs.getString(KEY_TRANSACTION_HISTORY, null) ?: return emptyList()
        return try {
            val type = object : TypeToken<List<Transaction>>() {}.type
            gson.fromJson(json, type)
        } catch (e: Exception) {
            emptyList()
        }
    }

    private fun loadRecentTransactionsMutable(): MutableList<Transaction> {
        return loadRecentTransactions().toMutableList()
    }

    /**
     * Formats a numeric amount for display.
     */
    private fun formatAmount(amount: Double): String {
        return if (amount == amount.toLong().toDouble()) {
            amount.toLong().toString()
        } else {
            String.format("%.2f", amount)
        }
    }
}
